// Generated by CoffeeScript 1.12.7
(function() {
  var app, express, http, path, port;

  path = require('path');

  express = require('express');

  app = express();

  http = require('http').Server(app);

  port = process.env.PORT || 3000;

  app.use('/css', express["static"](path.join(__dirname, '/public/assets/css')));

  app.use('/js', express["static"](path.join(__dirname, '/public/assets/js')));

  app.set('view engine', 'pug');

  require('./socket/index').listen(http);

  app.get('/', function(req, res) {
    return res.render('index');
  });

  http.listen(port, function() {
    return console.log('Listening on port ' + port + '...');
  });

}).call(this);
